### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by kemelzaidan** [smarteist/Pot-Translator#1]
Had the following error:
'''php
PHP Fatal error:  Uncaught TypeError: Gettext\Translation::translate(): Argument #1 ($translation) must be of type string, null given, called in /home/kemel/devel/src/Pot-Translator/src/CLI.php on line 216 and defined in /home/kemel/devel/src/Pot-Translator/vendor/gettext/gettext/src/Translation.php:173
Stack trace:
#0 /home/kemel/devel/src/Pot-Translator/src/CLI.php(216): Gettext\Translation->translate()
#1 [internal function]: App\CLI->translate()
#2 /home/kemel/devel/src/Pot-Translator/src/CLI.php(58): ReflectionMethod->invoke()
#3 /home/kemel/devel/src/Pot-Translator/pomo(5): App\CLI->bootstrap()
#4 {main}
  thrown in /home/kemel/devel/src/Pot-Translator/vendor/gettext/gettext/src/Translation.php on line 173
'''

 while trying to translate the  attached pot file (changet the extension to txt in order to upload to Github).
[com.github.bleakgrey.tootle.pot.txt](https://github.com/smarteist/Pot-Translator/files/10504330/com.github.bleakgrey.tootle.pot.txt)

Thanks for the awesome app!

**Comment by kemelzaidan** [comment]
I don't know what the problem was, but I'm not having it anymore...
